-- Closed-mode backlog item 379: CveOrgSyncService#syncBaseline/#syncDelta previously recorded
-- state (last_synced_at/last_release_tag) only on a fully successful run -- a download or parse
-- failure just logged an error and returned, leaving cve_org_sync_state completely untouched. A
-- mirror that fails every single day therefore left no signal anywhere in the DB: last_synced_at
-- stayed frozen at whatever the last real success was, and there was no way to tell "stale because
-- nobody has synced recently" apart from "stale because every recent attempt failed". Adds a
-- last_sync_error column, matching ghsa_sync_state/osv_sync_state's existing column of the same
-- name and purpose (see V19/V25's migration comments) -- CveOrgSyncService now updates
-- last_synced_at and this column on every attempt (success clears it, failure records a message),
-- so both /admin/cve-org and the item-382 mirror freshness check can see a stuck sync.
ALTER TABLE cve_org_sync_state ADD COLUMN last_sync_error TEXT;
